// <auto-generated />
namespace fIT.WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AlteredModels_WeightTimeStamp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlteredModels_WeightTimeStamp));
        
        string IMigrationMetadata.Id
        {
            get { return "201507150819282_AlteredModels_WeightTimeStamp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
