#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("fITNat.Resource", IsApplication=true)]

namespace fITNat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::fITNat.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::fITNat.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUpStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Check = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int CheckDouble = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit_text_style = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Email_envelope_16 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ProgressBarStyle = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000c
			public const int btnDialogEmail = 2131165196;
			
			// aapt resource value: 0x7f070002
			public const int btnDialogSignIn = 2131165186;
			
			// aapt resource value: 0x7f070027
			public const int btnSavePractice = 2131165223;
			
			// aapt resource value: 0x7f070018
			public const int btnSignIn = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int btnSignUp = 2131165210;
			
			// aapt resource value: 0x7f070016
			public const int ivConnection = 2131165206;
			
			// aapt resource value: 0x7f07000e
			public const int ivConnectionExcercise = 2131165198;
			
			// aapt resource value: 0x7f07001d
			public const int ivConnectionPractice = 2131165213;
			
			// aapt resource value: 0x7f070028
			public const int ivConnectionSchedule = 2131165224;
			
			// aapt resource value: 0x7f07000a
			public const int lblSpinFitness = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int lblSpinGender = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int lblSpinJob = 2131165192;
			
			// aapt resource value: 0x7f070010
			public const int lvExercise = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int lvSchedule = 2131165201;
			
			// aapt resource value: 0x7f07001b
			public const int progressBar1 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int rlPracticeLayout = 2131165212;
			
			// aapt resource value: 0x7f07000d
			public const int rlScheduleLayout = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int spinFitness = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int spinGender = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int spinJob = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int txtBirthdate = 2131165189;
			
			// aapt resource value: 0x7f070017
			public const int txtCreateAccount = 2131165207;
			
			// aapt resource value: 0x7f070003
			public const int txtEmail = 2131165187;
			
			// aapt resource value: 0x7f070013
			public const int txtExerciseViewDescription = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int txtExerciseViewID = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int txtExerciseViewName = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int txtExerciseViewScheduleID = 2131165205;
			
			// aapt resource value: 0x7f070026
			public const int txtNumberOfRepetitions = 2131165222;
			
			// aapt resource value: 0x7f070025
			public const int txtNumberOfRepetitionsLabel = 2131165221;
			
			// aapt resource value: 0x7f070019
			public const int txtOr = 2131165209;
			
			// aapt resource value: 0x7f070001
			public const int txtPassword = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int txtPasswordConfirm = 2131165188;
			
			// aapt resource value: 0x7f07001f
			public const int txtPracticeActual = 2131165215;
			
			// aapt resource value: 0x7f070024
			public const int txtRepetitions = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int txtRepetitionsLabel = 2131165219;
			
			// aapt resource value: 0x7f07002a
			public const int txtScheduleViewDescription = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int txtScheduleViewID = 2131165227;
			
			// aapt resource value: 0x7f07000f
			public const int txtTitleExercise = 2131165199;
			
			// aapt resource value: 0x7f07001e
			public const int txtTitlePractice = 2131165214;
			
			// aapt resource value: 0x7f070029
			public const int txtTitleSchedule = 2131165225;
			
			// aapt resource value: 0x7f070000
			public const int txtUsername = 2131165184;
			
			// aapt resource value: 0x7f070021
			public const int txtWeight = 2131165217;
			
			// aapt resource value: 0x7f070020
			public const int txtWeightLabel = 2131165216;
			
			// aapt resource value: 0x7f070022
			public const int txtWeightLabelSmall = 2131165218;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dialog_sign_in = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Dialog_sign_up = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ExerciseLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ExerciseView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PracticeLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ScheduleLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ScheduleView = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
